services:
  - type: web
    name: kudiescrow-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOW_DEV_RESET
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: kudiescrow-db
          property: connectionString
      - key: ADMIN_NAME
        value: Platform Admin
      - key: ADMIN_EMAIL
        value: admin@kudiescrow.local
      - key: ADMIN_PASSWORD
        value: ChangeMe123!
      - key: ADMIN_ROLE
        value: admin

databases:
  - name: kudiescrow-db
    databaseName: kudiescrow
    user: postgres
    plan: free
